name: Process Markdown Images on Push

on:
  push:
    branches:
      - main
    paths:
      - 'platform/**/**/*.md' # 只在 Markdown 文件变动时触发

jobs:
  process-images:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 授予写入权限，以便提交更改

    steps:
      # 1️⃣ 拉取代码
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取所有历史，以便进行 diff

      # 2️⃣ 设置 Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3️⃣ 安装依赖
      - name: Install dependencies
        run: pip install requests

      # 4️⃣ 获取本次 push 的 Markdown 文件
      - name: Detect changed Markdown files
        id: detect_md
        shell: bash
        run: |
          echo "::group::Detect changed .md files"
          changed=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.md$' || true)
          echo "Changed md files:"
          echo "$changed"
          echo "::endgroup::"

          # 将多行路径写入环境变量 CHANGED_MD_FILES
          if [[ -n "$changed" ]]; then
            echo "CHANGED_MD_FILES<<EOF" >> "$GITHUB_ENV"
            echo "$changed" >> "$GITHUB_ENV"
            echo "EOF" >> "$GITHUB_ENV"
          fi

      # 5️⃣ 处理每个 Markdown 文件
      - name: Process changed Markdown files
        shell: bash
        run: |
          if [[ -z "$CHANGED_MD_FILES" ]]; then
            echo "No changed Markdown files."
            exit 0
          fi

          echo "Processing changed Markdown files..."
          # 逐行读取环境变量
          while IFS= read -r f; do
            # 忽略空行
            [[ -z "$f" ]] && continue
            if [ -f "$f" ]; then
              echo "📄 Processing $f"
              python ./scripts/process_md_images.py "$f"
            else
              echo "⚠️ File not found: $f"
            fi
          done <<< "$CHANGED_MD_FILES"

      # 6️⃣ 提交并推送更新
      - name: Commit and push changes
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .

          if ! git diff --cached --quiet; then
            git commit -m "Auto-update local image paths for changed md files"
            git push origin main
          else
            echo "No changes to commit."
          fi
